[package]
name = "day15"
version = "0.1.0"
authors = ["Tom Rawcliffe <tom.rawcliffe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpds = "0.8.0"